INSERT INTO data_profesions(nombre) VALUES
    ('Médico'),
    ('Ingeniero'),
    ('Maestro'),
    ('Abogado'),
    ('Programador'),
    ('Enfermero'),
    ('Diseñador Gráfico'),
    ('Arquitecto'),
    ('Contador'),
    ('Chef'),
    ('Periodista'),
    ('Psicólogo'),
    ('Policía'),
    ('Científico'),
    ('Astrónomo'),
    ('Electricista'),
    ('Carpintero'),
    ('Plomero'),
    ('Músico'),
    ('Actor'),
    ('Camarero');
