INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Año nuevo', '2023-01-01', '2023-01-01', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de los Reyes Magos', '2023-01-09', '2023-01-09', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de San José', '2023-03-20', '2023-03-20', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Semana Santa', '2023-04-06', '2023-04-06', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Semana Santa', '2023-04-07', '2023-04-07', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Semana Santa', '2023-04-09', '2023-04-09', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de los Trabajadores', '2023-05-01', '2023-05-01', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de la Ascensión', '2023-05-22', '2023-05-22', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Corpus Christi', '2023-06-12', '2023-06-12', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día del Sagrado Corazón de Jesús', '2023-06-19', '2023-06-19', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de San Pedro y San Pablo', '2023-07-03', '2023-07-03', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Independencia de Colombia', '2023-07-20', '2023-07-20', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Batalla de Boyacá', '2023-08-07', '2023-08-07', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de la Asunción de la Virgen María', '2023-08-21', '2023-08-21', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de la Raza', '2023-10-16', '2023-10-16', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de todos los santos', '2023-11-06', '2023-11-06', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Independencia de Cartagena', '2023-11-13', '2023-11-13', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Día de la Inmaculada Concepción', '2023-12-08', '2023-12-08', NULL, NULL);
INSERT INTO `festivos` (`id`, `evento`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES (NULL, 'Navidad', '2023-12-25', '2023-12-25', NULL, NULL);
