INSERT INTO `modulos` (`id`, `nombre`, `descripcion`, `created_at`, `updated_at`) VALUES
    (NULL,'Ley de Protección de Datos Personales', 'Descripción de la Ley de Protección de Datos Personales', NULL, NULL),
    (NULL,'Términos y Condiciones', 'Descripción de los Términos y Condiciones', NULL, NULL),
    (NULL,'Días Festivos', 'Descripción de los Días Festivos', NULL, NULL),
    (NULL,'Profesiones', 'Descripción de las Profesiones', NULL, NULL),
    (NULL,'Tipo Contratos', 'Descripción de los Tipos de Contratos', NULL, NULL),
    (NULL,'Tipo Banco', 'Descripción de los Tipos de Banco', NULL, NULL),
    (NULL,'Tipo Jornada', 'Descripción de los Tipos de Jornada', NULL, NULL),
    (NULL,'Anexos', 'Descripción de los Anexos', NULL, NULL),
    (NULL,'Contratos', 'Descripción de los Contratos', NULL, NULL),
    (NULL,'Firmas', 'Descripción de las Firmas', NULL, NULL),
    (NULL,'Token de Seguridad', 'Descripción del Token de Seguridad', NULL, NULL),
    (NULL,'Usuarios del Sistema', 'Descripción de los Usuarios del Sistema', NULL, NULL),
    (NULL,'Departamentos', 'Descripción de los Departamentos', NULL, NULL),
    (NULL,'Municipios', 'Descripción de los Municipios', NULL, NULL),
    (NULL,'Países', 'Descripción de los Países', NULL, NULL),
    (NULL,'Modulos', 'Descripción de los Modulos', NULL, NULL),
    (NULL,'Mensajes', 'Descripción de los Mensajes', NULL, NULL),
    (NULL,'Tipo Mensaje', 'Descripción de los Tipo Mensaje', NULL, NULL),
    (NULL,'Tipo Entidades', 'Descripción de los Tipos de Entidades', NULL, NULL),
(NULL,'Fotos Perfil', 'Descripción de las Fotos Perfil', NULL, NULL);
