
INSERT INTO `p_q_r_d_s` (`id`, `n_peticion`, `peticion`, `respuesta`, `dias`, `dias_respuesta`, `fecha_vencimiento`, `nueva_peticion`, `resuelta`, `fecha_respuesta`, `usuario_peticionario`, `agente_servicio_cliente`, `created_at`, `updated_at`) VALUES
(1, 202403020001, 'Quiero expresar mi insatisfacción con el servicio que recibí en su restaurante \"La Parrilla Feliz\" ubicado en la Calle Principal. El sábado pasado, visité su establecimiento con mi familia y tuvimos una experiencia muy desagradable. La comida tardó más de una hora en ser servida, cuando finalmente llegó, estaba fría y mal preparada. Además, el personal de servicio fue grosero y poco atento a nuestras necesidades. Espero que tomen las medidas necesarias para mejorar la calidad del servicio y evitar que esto vuelva a ocurrir en el futuro.', 'Agradecemos sinceramente por tomarse el tiempo de hacernos saber sobre su experiencia en nuestro restaurante \"La Parrilla Feliz\". Lamentamos profundamente los inconvenientes que experimentó durante su última visita. La satisfacción de nuestros clientes es nuestra principal prioridad y nos tomamos muy en serio sus comentarios.', 0, 14, '2024-03-17', 0, 1, '2024-03-02', 'Juan Jose Diaz Betacourth', 'Juan Carlos Diaz Lara', '2024-03-03 01:17:15', '2024-03-03 23:18:16'),
(2, 202403020002, 'Quiero expresar mi insatisfacción con el servicio que recibí en su restaurante \"La Parrilla Feliz\" ubicado en la Calle Principal. El sábado pasado, visité su establecimiento con mi familia y tuvimos una experiencia muy desagradable. La comida tardó más de una hora en ser servida, cuando finalmente llegó, estaba fría y mal preparada. Además, el personal de servicio fue grosero y poco atento a nuestras necesidades. Espero que tomen las medidas necesarias para mejorar la calidad del servicio y evitar que esto vuelva a ocurrir en el futuro.', 'Hemos compartido su reclamo con nuestro equipo de gestión y estamos tomando las medidas necesarias para abordar los problemas que mencionó. Estamos investigando lo sucedido con el servicio de cocina y reentrenando a nuestro personal para garantizar que situaciones como estas no vuelvan a ocurrir en el futuro.', 0, 14, '2024-03-17', 0, 1, '2024-03-02', 'Juan Jose Diaz Betacourth', 'Juan Carlos Diaz Lara', '2024-03-03 01:21:40', '2024-03-03 23:18:16'),
(3, 202403020003, 'Quiero expresar mi insatisfacción con el servicio que recibí en su restaurante \"La Parrilla Feliz\" ubicado en la Calle Principal. El sábado pasado, visité su establecimiento con mi familia y tuvimos una experiencia muy desagradable. La comida tardó más de una hora en ser servida, cuando finalmente llegó, estaba fría y mal preparada. Además, el personal de servicio fue grosero y poco atento a nuestras necesidades. Espero que tomen las medidas necesarias para mejorar la calidad del servicio y evitar que esto vuelva a ocurrir en el futuro.', 'Además, nos gustaría ofrecerle una cena gratuita para cuatro personas en nuestro restaurante como una disculpa por su mala experiencia. Por favor, contáctenos para coordinar una fecha y hora conveniente para usted.', 0, 14, '2024-03-17', 0, 1, '2024-03-02', 'Juan Jose Diaz Betacourth', 'Juan Carlos Diaz Lara', '2024-03-03 01:22:19', '2024-03-03 23:18:16'),
(4, 202403020004, 'Quiero expresar mi insatisfacción con el servicio que recibí en su restaurante \"La Parrilla Feliz\" ubicado en la Calle Principal. El sábado pasado, visité su establecimiento con mi familia y tuvimos una experiencia muy desagradable. La comida tardó más de una hora en ser servida, cuando finalmente llegó, estaba fría y mal preparada. Además, el personal de servicio fue grosero y poco atento a nuestras necesidades. Espero que tomen las medidas necesarias para mejorar la calidad del servicio y evitar que esto vuelva a ocurrir en el futuro.', NULL, 0, 14, '2024-03-17', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 01:34:13', '2024-03-03 23:18:16'),
(5, 202403020005, 'Quiero expresar mi insatisfacción con el servicio que recibí en su restaurante \"La Parrilla Feliz\" ubicado en la Calle Principal. El sábado pasado, visité su establecimiento con mi familia y tuvimos una experiencia muy desagradable. La comida tardó más de una hora en ser servida, cuando finalmente llegó, estaba fría y mal preparada. Además, el personal de servicio fue grosero y poco atento a nuestras necesidades. Espero que tomen las medidas necesarias para mejorar la calidad del servicio y evitar que esto vuelva a ocurrir en el futuro.', NULL, 0, 14, '2024-03-17', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 01:35:44', '2024-03-03 23:18:16'),
(6, 202403030006, 'Plataformas como Twitter, Facebook, Instagram y LinkedIn ofrecen widgets que puedes integrar en tu sitio web para mostrar feeds, botones de compartir, botones de seguimiento, etc. Puedes obtener el código de incrustación directamente desde las plataformas de redes sociales y luego integrarlo en tu aplicación.', NULL, 16, NULL, '2024-03-01', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 11:34:18', '2024-03-03 23:18:16'),
(7, 202403030007, 'Hay varias bibliotecas de JavaScript que ofrecen widgets sociales personalizables. Algunas de las más populares incluyen AddThis, ShareThis, SocialShare.js, y muchos otros. Estas bibliotecas proporcionan herramientas para agregar botones de compartir, feeds de redes sociales, y otras funciones sociales a tu sitio web.', NULL, 7, NULL, '2024-02-21', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 11:39:18', '2024-03-03 23:18:16'),
(8, 202403030008, 'Existen varios plugins de jQuery y otras bibliotecas JavaScript que puedes utilizar para integrar widgets sociales en tu sitio web. Puedes buscar en sitios como GitHub o utilizar administradores de paquetes como npm para encontrar plugins que se ajusten a tus necesidades.', NULL, 4, NULL, '2024-02-18', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 11:39:52', '2024-03-03 23:18:16'),
(9, 202403030009, 'Una vez que hayas elegido la biblioteca o el método que deseas utilizar, puedes integrar los widgets sociales en tu aplicación AdminLTE 3 como lo harías con cualquier otro componente HTML o JavaScript. Recuerda seguir las instrucciones proporcionadas por la biblioteca o plataforma específica para configurar y personalizar tus widgets sociales según tus requisitos.', NULL, 13, NULL, '2024-02-27', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 11:40:28', '2024-03-03 23:18:16'),
(10, 202403030010, 'Los Zapatos Deportivos Nike Air Max 270 combinan un diseño moderno con tecnología de vanguardia para brindarte comodidad y estilo durante tus actividades deportivas o tu día a día. Confeccionados con materiales de alta calidad, estos zapatos ofrecen una mezcla perfecta de amortiguación, sujeción y transpirabilidad.', NULL, 6, NULL, '2024-02-20', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 11:42:05', '2024-03-03 23:18:16'),
(11, 202403030011, 'La parte superior de malla transpirable proporciona una ventilación óptima para mantener tus pies frescos, mientras que la tecnología Nike Air en el talón ofrece una amortiguación excepcional y una sensación de ligereza en cada paso. La suela de goma duradera cuenta con un diseño tipo gofre que brinda tracción y agarre en una variedad de superficies, desde la pista hasta la calle', NULL, 10, NULL, '2024-02-24', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 11:42:36', '2024-03-03 23:18:16'),
(12, 202403030012, 'El Padrino\" es una obra maestra del cine dirigida por Francis Ford Coppola, basada en la novela de Mario Puzo. Ambientada en el oscuro y peligroso mundo de la mafia italiana en Nueva York, la película narra la historia de la familia Corleone y su ascenso al poder en el crimen organizado.', NULL, 0, NULL, '2024-02-14', 1, 0, NULL, 'Juan Jose Diaz Betacourth', NULL, '2024-03-03 11:43:23', '2024-03-03 23:18:16');

